spring:
  datasource:
    url: "jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=public"
    username: "postgres.kravlhhwqophgsxrdodk"
    password: "Khiem792k5@"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false

server:
  port: 8080

app:
  jwt:
    secret: "lemondesteak-change-this-to-a-long-random-secret-key-at-least-32-chars"
    expiration-minutes: 1440
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:3000,http://127.0.0.1:5173"
